// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH-4PfXiyx7nocl63hlHr4karPhEY-rCs',
    appId: '1:873964715338:web:c7c34f7b14173299d615b3',
    messagingSenderId: '873964715338',
    projectId: 'testprojectfb2',
    authDomain: 'testprojectfb2.firebaseapp.com',
    storageBucket: 'testprojectfb2.appspot.com',
    measurementId: 'G-B0FN34XMY5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC_HrlKePkZYDyNF_fHfHIPW59W3zO7xs',
    appId: '1:873964715338:android:f7b2e74094aa8bf5d615b3',
    messagingSenderId: '873964715338',
    projectId: 'testprojectfb2',
    storageBucket: 'testprojectfb2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlXUa4ib3wksqX_RRiEOVfwUeYrXK9a7I',
    appId: '1:873964715338:ios:86bd3b3578a54b0ed615b3',
    messagingSenderId: '873964715338',
    projectId: 'testprojectfb2',
    storageBucket: 'testprojectfb2.appspot.com',
    iosBundleId: 'com.example.testProjectFb2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlXUa4ib3wksqX_RRiEOVfwUeYrXK9a7I',
    appId: '1:873964715338:ios:49c6d7b4b1b9e1cfd615b3',
    messagingSenderId: '873964715338',
    projectId: 'testprojectfb2',
    storageBucket: 'testprojectfb2.appspot.com',
    iosBundleId: 'com.example.testProjectFb2.RunnerTests',
  );
}
